export { SearchIconTemplate } from './SearchIconTemplate';
export { AddIconTemplate } from './AddIconTemplate';
export { HomeIconTemplate } from './HomeIconTemplate';
export { DeleteIconTemplate } from './DeleteIconTemplate';
export { EditIconTemplate } from './EditIconTemplate';
export { ScheduleIconTemplate } from './ScheduleIconTemplate';
export { MoreVertIconTemplate } from './MoreVertIconTemplate';
export { CloseIconTemplate } from './CloseIconTemplate';
export { ErrorIconTemplate } from './ErrorIconTemplate';
